---
title: "Week 03 Assignment"
author: Michael Smith
email: cornell.smith@wsu.edu
course: "STATS 419 Survey Multivariate Analysis"
instructor: "Monte J. Shaffer"
date: "r format(Sys.time(),'%d %B %Y')"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r}
library(devtools); # devtool requird for source function to operate properly
my.source = 'github'
github.path = "https://raw.githubusercontent.com/madhatter2012/WSU_STATS419_FALL2020/";
source_url( paste0(github.path,"master/functions/libraries.R") );
source_url( paste0(github.path,"master/functions/functions-imdb.R") );

```



# 1. Create the "rotate matrix" functions as described in lectures.  Apply to the example "myMatrix".

```{r}

# Function to transpose matrix
transposeMatrix = function(mat)
  {
  t(mat);	
	}

# rotae matrix 90 degrees				
rotateMatrix90(mat)	= function(mat)
	{
	t(myMatrix[nrow(myMatrix):1,]);
	}

# rotae matrix 180 degrees
rotateMatrix180(mat) = function(mat)
  {
myMatrix[nrow(myMatrix):1,ncol(myMatrix):1];
  }	


rotateMatrix270(mat) = function(mat)
					{
					t(myMatrix)[ncol(myMatrix):1,];
					}

```


















## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```
